#include "sam3.h"

#include <cassert>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// ── Test cases with Python-verified expected token IDs ───────────────────────
// Generated by: python scripts/verify_tokenizer.py raw_weights/

struct test_case {
    const char * text;
    std::vector<int32_t> expected;  // non-padding tokens only (SOT + BPE + EOT)
};

static const test_case CASES[] = {
    { "a",                 { 49406, 320, 49407 } },
    { "hello world",       { 49406, 3306, 1002, 49407 } },
    { "yellow school bus", { 49406, 4481, 1228, 2840, 49407 } },
    { "a photo of a cat",  { 49406, 320, 1125, 539, 320, 2368, 49407 } },
    { "don't stop",        { 49406, 847, 713, 1691, 49407 } },
    { "SAM 3",             { 49406, 3730, 274, 49407 } },
    { "123",               { 49406, 272, 273, 274, 49407 } },
    { "",                  { 49406, 49407 } },
    { "a person riding a bicycle on a sunny day in the park",
      { 49406, 320, 2533, 6765, 320, 11652, 525, 320, 5438, 575, 530, 518, 1452, 49407 } },
};
static const int N_CASES = sizeof(CASES) / sizeof(CASES[0]);

int main(int argc, char ** argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <model.ggml>\n", argv[0]);
        return 1;
    }

    if (!sam3_test_load_tokenizer(argv[1])) {
        fprintf(stderr, "FAIL: could not load tokenizer from '%s'\n", argv[1]);
        return 1;
    }

    int n_pass = 0;
    for (int i = 0; i < N_CASES; ++i) {
        auto tokens = sam3_test_tokenize(CASES[i].text);
        const auto & exp = CASES[i].expected;
        bool pass = true;

        // Must be exactly 32 tokens (context length)
        if ((int)tokens.size() != 32) {
            fprintf(stderr, "FAIL [%d]: expected 32 tokens, got %d\n", i, (int)tokens.size());
            pass = false;
        }

        // Check non-padding prefix matches expected exactly
        for (size_t j = 0; j < exp.size() && j < tokens.size(); ++j) {
            if (tokens[j] != exp[j]) {
                fprintf(stderr, "FAIL [%d]: token[%zu] = %d, expected %d\n",
                        i, j, tokens[j], exp[j]);
                pass = false;
            }
        }

        // Check remaining positions are zero-padded
        for (size_t j = exp.size(); j < tokens.size(); ++j) {
            if (tokens[j] != 0) {
                fprintf(stderr, "FAIL [%d]: expected 0 at position %zu, got %d\n",
                        i, j, tokens[j]);
                pass = false;
                break;
            }
        }

        // Print result
        fprintf(stderr, "%s [%d] \"%s\" → [", pass ? "PASS" : "FAIL", i, CASES[i].text);
        for (size_t j = 0; j < tokens.size(); ++j) {
            if (j > 0) fprintf(stderr, ", ");
            fprintf(stderr, "%d", tokens[j]);
            if (tokens[j] == 0 && j > 1) { fprintf(stderr, ", ..."); break; }
        }
        fprintf(stderr, "]\n");

        if (pass) n_pass++;
    }

    fprintf(stderr, "\n%d/%d tests passed\n", n_pass, N_CASES);
    return (n_pass == N_CASES) ? 0 : 1;
}
